### ISSUE TITLE
SSL support for HTTP endpoints?

### ISSUE THREAD

**Issue by huglester** [meterio/WarringStakes#10]
Hello

I wonder if its good idea to:
protect all endpoints with SSL (using letsencrypt)? 

Of course it will add some SSL overhead and so on. But in general will be more secure? 

Thanks

**Comment by xiaohanzhu** [comment]
yes, it is possible, but since all the messages were encrypted already.  SSL probably will not give you any gains

**Comment by huglester** [comment]
thanks
