### ISSUE TITLE
Can't Claim Test Token

### ISSUE THREAD

**Issue by Wangmmx** [meterio/WarringStakes#15]
Can not claim test token in http://faucet.meter.io/, always report 504 error

**Comment by Wangmmx** [comment]
Is it my network problem or the faucet is not available now? Thanks

**Comment by xiaohanzhu** [comment]
You will have to use the warringstakes testnet.  The faucet is stopped for now as we are launching mainnet this week.   Please join our wechat group or discord channel if you need test tokens
