### ISSUE TITLE
[BUG] Transaction links in activities section of wallet

### ISSUE THREAD

**Issue by mstephen5** [meterio/WarringStakes#4]
Clicking on transaction links in "activities" section of wallet leads to wrong URL. Results in 404 error.

![Annotation 2019-12-17 175323](https://user-images.githubusercontent.com/58920370/71022357-45864280-20ce-11ea-8421-ef2631debdca.png)
![Annotation 2019-12-17 175324](https://user-images.githubusercontent.com/58920370/71022365-4a4af680-20ce-11ea-8dbb-791f46c234d9.png)

**Comment by xiaohanzhu** [comment]
Fixed.  Please download the latest wallet.  You may want to update the testnet docker image as well later.  There were some updates.  I will put in update instructions in README.md tomorrow
