### ISSUE TITLE
node sync blockchain stuck at 158,461

### ISSUE THREAD

**Issue by xunppchen** [meterio/WarringStakes#7]
run node from fresh but stuck at 158,461

![meter io](https://user-images.githubusercontent.com/38031058/71121672-3511bd00-21df-11ea-9423-3e37abb95a14.JPG)

some log file
[pos-stderr---supervisorae.log](https://github.com/meterio/WarringStakes/files/3980506/pos-stderr---supervisorae.log)
[pos-stdout---supervisor-ad.log](https://github.com/meterio/WarringStakes/files/3980507/pos-stdout---supervisor-ad.log)

**Comment by xiaohanzhu** [comment]
we put the testnet in maintenance mode as some of the 3rd party validators were misconfigured after docker image update.  Stay tuned.  Will get it back up in a few hours

**Comment by xiaohanzhu** [comment]
we are back online now.  Feel free to try again.  Recommend to pull the updated docker image

**Comment by xiaohanzhu** [comment]
were you able to get it running?  don't forget to comment on the issue 1 on your validator name and machine configuration
